- hosts: baseRH7
  vars:  
#   _uid: ""
#   _pwd: ""
    custom_repo: true
#   java_link: https://drive.google.com/open?id=1bSq7I3MY3SvY4MHfowEyNq3l-sFMJa8B
#   java_archive: jdk-8u201-linux-x64.tar.gz
#   download_url: https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
  vars_files:
    - ~/RHACCOUNT
  become: yes
  become_method: sudo
  pre_tasks:
    - debug:
        msg: "Variables: _uid = {{ _uid }}, _pwd = {{ _pwd }}"    
    - name: register RHEL7.5
      command: "/usr/bin/subscription-manager register --username {{ _uid }} --password {{ _pwd }} --auto-attach"
#     command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-7-rpms"
    - name: register RHEL7 Satellite Repo 
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-satellite-6.4-rpms --enable=rhel-7-server-satellite-maintenance-6-rpms"
    - name: register RHEL7 Ansible Repo 
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-ansible-2.6-rpms"
    - name: register RHEL7 DevTools
      command: "/usr/bin/subscription-manager repos --enable=rhel-7-server-devtools-rpms"
    - name: list RHEL enabled repos
      command: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}"    
#   - name: list available repos
#     command: /usr/bin/subscription-manager repos --list
#     register: repos_list
#   - debug:
#       msg: "RH Repolist: {{ repos_list }}"
#       verbosity: 3
  tasks:
    - name: install libselinux-python
      yum:
        name: libselinux-python
        state: present      
    - name: install DevTools-7
      yum:
        name: devtoolset-7      
        state: present

    - name: download epel
      shell:  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -O /tmp/epel-release-latest-7.noarch.rpm   
    - name: Install epel
      shell:  yum -y localinstall /tmp/epel*rpm
    - name: Install python-pip
      yum:
        name: python-pip
        state: latest
        
    - name: install satellite
      yum:
        name: satellite
        state: latest
        
#   - name: install gdown
#     shell: pip install gdown
#   - name: use gdown to download jdk1.8.x from google drive
#     shell: gdown https://drive.google.com/uc?id=1bSq7I3MY3SvY4MHfowEyNq3l-sFMJa8B
#   - name: install createrepo
#     yum:
#       name: createrepo
#       state: latest
#   - name: create local repo 
#     shell: createrepo /opt/devrepo-master/Packages
#   - name: create local repo file with updated link
#     file:
#       path: /etc/yum.repos.d/local.repo
#       state: touch
#       mode: "u=rw,g=r,o=r" 
#   - name: edit local.repo file
#     shell: |
#       echo '[localrepo]\n
#       name=localrepo\n
#       baseurl=file:///opt/devrepo-master/Packages\n
#       enabled=1\n
#       gpgcheck=0\n' >> /etc/yum.repos.d/local.repo
 
# roles:
#   - umask
#   - devtools
  post_tasks:
    - name: remove RHEL7.5
      command:  "/usr/bin/subscription-manager remove --all"
    - name: unregister RHEL7.5
      command:  "/usr/bin/subscription-manager unregister"
    - name: clean RHEL7.5
      command:  "/usr/bin/subscription-manager clean"
